CXX= g++
CXXFLAGS= -Iinclude
SRC_DIR = src
SRCS := $(wildcard *.cpp)

# SRCS = src/rnt.cpp \
       src/rnt-mainapp.cpp \
       src/rnt-enum.cpp \
       src/rnt-texteditor.cpp \
       src/rnt-sys.cpp \
       src/rnt-configurator.cpp \
       
       src/rnt-main.cpp 
OBJ=build/obj

OBJS=$(SRCS:.cpp=.o) 
TARGET=build/rnt

.PHONY: all clean

show_o:
	@echo $(OBJS)
show_s:
	@echo $(SRCS)

all: $(TARGET)

%.o: %.cpp
	@echo "[--] Building object $@"
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
